# Generated by Django 3.0 on 2019-12-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('beginning_date', models.DateField()),
                ('actual_expiration_date', models.DateField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LaborCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_hours', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('beginning_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.Position')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tasks',
            field=models.ManyToManyField(to='HRMS.Task'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('beginning_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee')),
            ],
        ),
    ]
