# Generated by Django 3.0 on 2019-12-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
