# Generated by Django 3.0 on 2019-12-07 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMS', '0002_auto_20191207_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='login',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
