# Generated by Django 3.0 on 2019-12-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0002_foreignlanguage_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignlanguage',
            name='test',
        ),
    ]
