# Generated by Django 3.0 on 2019-12-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0003_auto_20191207_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='tasks',
            new_name='task',
        ),
    ]
