# Generated by Django 3.0 on 2019-12-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0003_remove_foreignlanguage_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='language_name',
            field=models.CharField(choices=[('Английский', 'Английский'), ('Немецкий', 'Немецкий'), ('Испанский', 'Испанский'), ('Китайский', 'Китайский'), ('Французский', 'Французский')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True),
        ),
    ]
