# Generated by Django 3.0 on 2019-12-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0004_auto_20191220_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.CharField(choices=[('Программирование', 'Программирование'), ('Тестирование', 'Тестирование'), ('Системное администрирование', 'Системное администрирование'), ('SAP', 'SAP')], max_length=50, null=True),
        ),
    ]
