# Generated by Django 3.0 on 2019-12-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0008_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee'),
            preserve_default=False,
        ),
    ]
