# Generated by Django 3.0 on 2019-12-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0009_auto_20191221_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='course',
            new_name='course_required',
        ),
        migrations.AddField(
            model_name='position',
            name='education_required',
            field=models.CharField(choices=[('Высшее образование', 'Высшее образование'), ('Среднее образование', 'Среднее образование')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='experience_required',
            field=models.CharField(choices=[('Опыт работы не требуется', 'Опыт работы не требуется'), ('1 год', '1 год'), ('2 года', '2 года'), ('3 года', '3 года'), ('4 года', '4 года'), ('5 и более лет', '5 и более лет')], max_length=50, null=True),
        ),
    ]
