# Generated by Django 3.0 on 2019-12-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0009_experience_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='HRMS.Employee'),
        ),
    ]
