# Generated by Django 3.0 on 2019-12-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0010_auto_20191221_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='education_required',
            field=models.CharField(choices=[('Образование не требуется', 'Образование не требуется'), ('Высшее образование', 'Высшее образование'), ('Среднее образование', 'Среднее образование')], max_length=50, null=True),
        ),
    ]
