# Generated by Django 3.0 on 2019-12-09 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0011_auto_20191209_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee'),
        ),
    ]
