# Generated by Django 3.0 on 2019-12-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0012_auto_20191222_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education_type',
            field=models.DecimalField(choices=[(2, 'Высшее образование'), (1, 'Среднее образование')], decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='level',
            field=models.DecimalField(choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1'), (6, 'C2')], decimal_places=0, max_digits=5, null=True),
        ),
    ]
