# Generated by Django 3.0 on 2019-12-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0012_auto_20191209_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='laborcosts',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='HRMS.Education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='HRMS.Experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='laborcosts',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='HRMS.LaborCosts'),
            preserve_default=False,
        ),
    ]
