# Generated by Django 3.0 on 2019-12-09 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0013_auto_20191209_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborcosts',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMS.Task'),
        ),
    ]
