# Generated by Django 3.0 on 2019-12-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0014_auto_20191224_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignlanguage',
            name='language_name',
            field=models.CharField(choices=[('Английский', 'Английский'), ('Немецкий', 'Немецкий'), ('Испанский', 'Испанский'), ('Китайский', 'Китайский'), ('Французский', 'Французский')], max_length=30, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='level',
            field=models.DecimalField(choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1'), (6, 'C2')], decimal_places=0, max_digits=5, null=True, verbose_name='Уровень знания языка'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='emotionality',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Эмоционально устойчивый - эмоциональный'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='self_centeredness',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Ориентированный на группу - ориентированный на себя'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='smart',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Менее сообразительный - более сообразительный'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='sociability',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Замкнутость - общительность'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='tension',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Раскованный - напряженный'),
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractiveness', models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Менее привлекательный - более привлекательный')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee')),
            ],
        ),
    ]
