# Generated by Django 3.0 on 2019-12-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0014_auto_20191210_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='laborcosts',
        ),
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laborcosts',
            name='employee',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee'),
            preserve_default=False,
        ),
    ]
