# Generated by Django 3.0 on 2019-12-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0015_auto_20191224_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='looseness',
        ),
        migrations.AddField(
            model_name='employee',
            name='tension',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Раскованный - напряженный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emotionality',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Эмоционально устойчивый - эмоциональный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='self_centeredness',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Ориентированный на группу - ориентированный на себя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='smart',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Менее сообразительный - более сообразительный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sociability',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Замкнутость - общительность'),
        ),
    ]
