# Generated by Django 3.0 on 2019-12-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0016_auto_20191224_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personality',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='attractiveness',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Менее привлекательный - более привлекательный'),
        ),
        migrations.DeleteModel(
            name='Appearance',
        ),
        migrations.DeleteModel(
            name='Personality',
        ),
    ]
