# Generated by Django 3.0 on 2019-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0016_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='emp_img.jpg', upload_to='employee_pics'),
        ),
    ]
