# Generated by Django 3.0 on 2019-12-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0017_auto_20191224_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='attractiveness',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Менее привлекательный, 7 - более привлекательный'),
        ),
        migrations.AddField(
            model_name='position',
            name='emotionality',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Эмоционально устойчивый, 7 - эмоциональный'),
        ),
        migrations.AddField(
            model_name='position',
            name='self_centeredness',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Ориентированный на группу, 7 - ориентированный на себя'),
        ),
        migrations.AddField(
            model_name='position',
            name='smart',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Менее сообразительный, 7 - более сообразительный'),
        ),
        migrations.AddField(
            model_name='position',
            name='sociability',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Замкнутый, 7 - общительный'),
        ),
        migrations.AddField(
            model_name='position',
            name='tension',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Раскованный, 7 - напряженный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='attractiveness',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Менее привлекательный, 7 - более привлекательный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emotionality',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Эмоционально устойчивый, 7 - эмоциональный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='self_centeredness',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Ориентированный на группу, 7 - ориентированный на себя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='smart',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Менее сообразительный, 7 - более сообразительный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sociability',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Замкнутый, 7 - общительный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tension',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5'), (4, '6'), (4, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Раскованный, 7 - напряженный'),
        ),
    ]
