# Generated by Django 3.0 on 2019-12-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0018_auto_20191224_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborcosts',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='laborcosts',
            name='task',
        ),
        migrations.RemoveField(
            model_name='position',
            name='course_required',
        ),
        migrations.AlterField(
            model_name='education',
            name='beginning_date',
            field=models.DateField(null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_type',
            field=models.DecimalField(choices=[(2, 'Высшее образование'), (1, 'Среднее образование')], decimal_places=0, max_digits=3, null=True, verbose_name='Тип образования'),
        ),
        migrations.AlterField(
            model_name='education',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='education',
            name='faculty',
            field=models.CharField(max_length=100, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название учебного заведения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialty',
            field=models.CharField(max_length=100, null=True, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emotionality',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Эмоционально устойчивый, 7 - эмоциональный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=30, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='emp_img.jpg', upload_to='employee_pics', verbose_name='Фотография сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRMS.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='self_centeredness',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Ориентированный на группу, 7 - ориентированный на себя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='smart',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Менее сообразительный, 7 - более сообразительный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sociability',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Замкнутый, 7 - общительный'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tension',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Раскованный, 7 - напряженный'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='beginning_date',
            field=models.DateField(null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job',
            field=models.CharField(max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='position',
            name='attractiveness',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Менее привлекательный, 7 - более привлекательный'),
        ),
        migrations.AlterField(
            model_name='position',
            name='education_required',
            field=models.DecimalField(choices=[(0, 'Образование не требуется'), (1, 'Среднее образование'), (2, 'Высшее образование')], decimal_places=0, max_digits=3, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='position',
            name='emotionality',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Эмоционально устойчивый, 7 - эмоциональный'),
        ),
        migrations.AlterField(
            model_name='position',
            name='experience_required',
            field=models.DecimalField(choices=[(0, 'Опыт работы не требуется'), (1, '1 год'), (2, '2 года'), (3, '3 года'), (4, '4 года'), (5, '5 и более лет')], decimal_places=0, max_digits=3, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='position',
            name='foreign_language',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Английский', 'Английский'), ('Немецкий', 'Немецкий'), ('Испанский', 'Испанский'), ('Китайский', 'Китайский'), ('Французский', 'Французский')], max_length=40, null=True, verbose_name='Иностранный язык'),
        ),
        migrations.AlterField(
            model_name='position',
            name='language_level',
            field=models.DecimalField(blank=True, choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1'), (6, 'C2')], decimal_places=0, max_digits=3, null=True, verbose_name='Уровень знания языка'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='position',
            name='self_centeredness',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Ориентированный на группу, 7 - ориентированный на себя'),
        ),
        migrations.AlterField(
            model_name='position',
            name='smart',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Менее сообразительный, 7 - более сообразительный'),
        ),
        migrations.AlterField(
            model_name='position',
            name='sociability',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Замкнутый, 7 - общительный'),
        ),
        migrations.AlterField(
            model_name='position',
            name='tension',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - Раскованный, 7 - напряженный'),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_expiration_date',
            field=models.DateField(blank=True, verbose_name='Дата фактического завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='beginning_date',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='Код задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(null=True, verbose_name='Крайний срок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='LaborCosts',
        ),
    ]
