# Generated by Django 3.0 on 2019-12-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0019_remove_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, null=True)),
                ('specialization', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_expiration_date',
            field=models.DateField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=30, null=True)),
                ('level', models.CharField(max_length=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee')),
            ],
        ),
    ]
