# Generated by Django 3.0 on 2019-12-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0019_auto_20191225_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=50, null=True, verbose_name='Название навыка')),
                ('value', models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=5, null=True, verbose_name='Уровень владения навыком')),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='position',
        ),
        migrations.RemoveField(
            model_name='foreignlanguage',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='position',
            name='education',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='position',
            name='experience',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emotionality',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - эмоциональный, 7 - Эмоционально устойчивый'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tension',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - напряженный, 7 - Раскованный'),
        ),
        migrations.AlterField(
            model_name='position',
            name='education_required',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='position',
            name='emotionality',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - эмоциональный, 7 - Эмоционально устойчивый'),
        ),
        migrations.AlterField(
            model_name='position',
            name='experience_required',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='position',
            name='foreign_language',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], max_length=40, null=True, verbose_name='Иностранный язык'),
        ),
        migrations.AlterField(
            model_name='position',
            name='language_level',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='Уровень знания языка'),
        ),
        migrations.AlterField(
            model_name='position',
            name='tension',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, max_digits=3, null=True, verbose_name='1 - напряженный, 7 - Раскованный'),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='ForeignLanguage',
        ),
        migrations.AddField(
            model_name='requirements',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.Employee'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMS.Position'),
        ),
    ]
