# Generated by Django 3.0 on 2019-12-26 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0020_auto_20191227_0144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirements',
            new_name='Requirement',
        ),
    ]
