# Generated by Django 3.0 on 2019-12-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS', '0021_auto_20191227_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='position',
            name='education',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='position',
            name='experience',
            field=models.DecimalField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Опыт работы'),
        ),
    ]
